name: quick_cars_service
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.3+13

environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # Loading Widget
  flutter_easyloading: ^3.0.5
  # Text Font Style
  google_fonts: ^6.2.1
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Api Calling
  freezed_annotation: ^2.4.4
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  get_it: ^7.6.7
  dartz: ^0.10.1
  # Toast Message Widget
  fluttertoast:
  # Navigation
  page_transition: ^2.1.0
  # Localization
  easy_localization: ^3.0.8
  flutter_phoenix: ^1.1.1
  # Storage
  flutter_secure_storage: ^9.2.2
  multi_select_flutter: ^4.1.3
  # pusher
  pusher_channels_flutter: ^2.2.0
  # image
  image_picker: ^1.1.2
  photo_view: ^0.14.0
  webview_flutter: ^4.13.0
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  pdf: ^3.11.3
  http: ^1.6.0
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-Regular.ttf
        - asset: assets/fonts/Almarai-Bold.ttf
